#ENC[AES256_GCM,data:x351iGEz4lpyACYMXG2QjifyoV6HAe+n8D+msM2nnJVfANRVadz4gh1uCb5GbMIibNfX2fj8lnhOwS9C/NMPvsDvwPPaLvMObBZgaIVYfarpEN1P59v8GTYFq/6ZQIIxua0+/LgWpbkWG+zRzhlGiBp54Q==,iv:XHdYEmeilH7YcbRBMhw8Jhwj4DmNfcZFJ7Vw9lOF+lw=,tag:WeRnw0MjrVT6rCKyZ5wZvA==,type:comment]
image:
    #ENC[AES256_GCM,data:LrXWN1ar7NDEGj/GHJHwrTg=,iv:ybidNBGXXLcrpmNWpXusDJntp7p0Gr8gkTzkhHN9N/k=,tag:IscALHdV7JCXRelyX1qv2Q==,type:comment]
    repository: ENC[AES256_GCM,data:2+6byOYy7UItsHY8YkA=,iv:hSWJ9+bux0sjMypz2DBbHdPtjCBRsjOvyUF2grcqw14=,tag:QpaahGbHD723Wi+1ontY8Q==,type:str]
    #ENC[AES256_GCM,data:EJ0vqiXaUNHrUg==,iv:jGoxkLOML/og2lF01aNIH75CVCl+PTh+c8CJzuMO0Ho=,tag:jWbKQsPP47LMWFt68iE1Og==,type:comment]
    tag: ENC[AES256_GCM,data:SV5y/X+H,iv:xdpoOqWx8kOxBdM8BS7OO8bpuvS6QlqCYUU6VAURsBQ=,tag:WyRe6VC+GU2feH7/5qmDCQ==,type:str]
#ENC[AES256_GCM,data:hjSNDs5nvJkMANUDSUfbidQGJEEVB5+hhuwnFLFNBM5owzP4mcTPK2R6JD9EO4czTyaDzkVYVtRgA+ei2ZwUg1otv1TpCKhT9pk79SfL,iv:LPTG8d3PsO/CLUE9LHw6+Ab/NrwxNTL895SWJKuy9VM=,tag:/LRmXtDIY5JT/a2I7DhjoA==,type:comment]
hostname: null
#ENC[AES256_GCM,data:vp7iAxl7TiC2qWEMm4B09wEASvFEhDV7rrPD,iv:H7+lHF2dD04l5YRrCT9iw82Ajm73Oob9Jxf7GSRDIUg=,tag:gVMnbCt2MVs+PrGzjwC8kA==,type:comment]
port: null
#ENC[AES256_GCM,data:gHi/tyIk8BInOgfLD4MuOuYAoi+F9dShQVtcBh8NpUzzj2OfJnqEZUf1KgNJTtIeTuxzdMGoL+51L6IKfMzqS6I=,iv:qmZnfqqUzTzcK/GHqELNyn9bmmostT31vCG/KTR91j0=,tag:GDfmGnWNO5WzuOE6D0vO0w==,type:comment]
traefik:
    enabled: ENC[AES256_GCM,data:d/jTV6o=,iv:ogSpBfoBQN3B7oypaN0OkRDzPbqoDaXUhtVno9dvD6c=,tag:jB28ajouWbOda/2Wrxmtxw==,type:bool]
    middlewares: null
    network: ENC[AES256_GCM,data:1NlAaloKSg==,iv:JZp1XQH/dyyrfLkJoTuz0AS+gkGmNMp7jri2qvUl5w8=,tag:dFWafaeasBiRYsQBw7GkhA==,type:str]
    tls:
        enabled: ENC[AES256_GCM,data:e4CsJqE=,iv:WyJS/7cUnLsEf35ooTHACyHVD8JJTBDaS1fOd/kWz+E=,tag:HZvcKQxigegjBjzSGnkivw==,type:bool]
        certresolver: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjzcc45rq3rlnt0hd6a77w9p90pdzmq3df7pdgtkrhynyxs25y2qltryk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ2J4eWZMdjFhMHNHb0xI
            SWMxejM2bnhTdU5QSndYKytEbDlSY3I1Y0NZCjNQU21sN0Z0dFU2ckxNckdYZjdn
            U1UrZjlWZkpmR2xhcGJCazNKQWt6K1EKLS0tIENvYjM5UVZ0REJBU2dtajJPNkNa
            Z1BKUmpDUGFxUmpqeGppV3RRUUVrU2sKx/N6obfazescA5AWMytf5Eq/SfmQp9Uh
            qZcmv6iWOEzJ1bIEF/2qkqiybTROkbE3XsAHAewt9SR9cGsM3AVY8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T18:16:40Z"
    mac: ENC[AES256_GCM,data:m8HItdayQx/uzhf7yROoDuifeQ1uUNjX/40o4ITDOg4jmBya09OKAkYDWGYCfxsTztwBAQRYYTHOQWsEoRqe/7xPR4jTyBAxFHyJ6YhX40uybARuNIt36cyYwyYqHAWNV1IERSMMw4f5s7pGrz7IdeFWQH5GWb56lqVuPz9/V3w=,iv:kh7qXr7ynRBVToNlrDFq8Mr0EYK1XdGCPOI4dYy2g30=,tag:DuiI/D57qJmqnnh+pctt7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
